# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on:
  pull_request:
    branches:
      - devel

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
          overwrite: true
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE/devel

    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build pOLT Simulator
      run: |
        echo Building pOLT Simulator in $GITHUB_WORKSPACE/build ..
        make CCACHE=n
        echo pOLT Simulator built successfully. 
        echo Build artifacts can be found in $GITHUB_WORKSPACE/build/fs

    - uses: actions/upload-artifact@v1
      if: success()
      with:
        name: build-artifacts
        path: build/fs
    
